#
# "databasepkdnn" permits to create a series of binary files that forms the database. The database is used for training the pkdnn
#

# Inputs to be considered in the database
# the available inputs are:
# 'energy', 'slab_thickness', 'dist_source_tally', 'delta_t', 'angle', 'theta', 'fi', 'dist_source_wall', 'dist_wall_tally', 'mfp'
inputs : ['energy', 'dist_source_tally', 'dist_wall_tally', 'mfp', 'theta', 'fi']

# Output to be considered in the database
# the available outputs are:
# 'B', 'Dose'
output : 'B'


# Path to the folder in which to save files of the database
database_folder_path: ""

# Path to the folder in which are stored MCNP results in binary file
raw_path : \Users\mario\OneDrive\Desktop\UNED\Phd\PointKernelMethod\PKnn\examples\data_example\raw

# Number of mesh subdivisions on x, y and z 
mesh_dim: [80,100,35]


# Specifics to irradiation configuration
p0 : 2000
wall_normal : [0,1,0]
source : [0,0,500]


# Wall material
atomic_number: [ 1, 8, 11, 12, 13, 14, 16, 19, 20, 26]
mass_fraction: [0.0056, 0.497500, 0.017100, 0.002600, 0.046900, 0.314700, 0.001300, 0.019200, 0.082800, 0.012400]
# density
ro : 2.2


# Path to coefficients used in calculation
# Flux to dose conversion coefficient
path_to_dose_conversion : \Users\mario\OneDrive\Desktop\UNED\Phd\PointKernelMethod\NN\data\Coeffs\doseEquivalentConversion.txt
# Mass attenuation coefficient
path_to_mass_att_coeff : \Users\mario\OneDrive\Desktop\UNED\Phd\PointKernelMethod\NN\data\Coeffs\massAttCoeff.xml



