#' Paths to input and output quantities for processing predictions.
#' In this case, the inputs are a trained neural network and the relative scaler file, which
#' contains informations on how to scale inputs/output sequences,
#' while the output are the neural networks predicitons.
io_paths:
  #' Path in which to save results
  save_path: ""
  #' Path in which the trained neural network is saved (as a '.pt' file) 
  path_to_model: \absolute\path\to\neuralnet\NNmodel.pt
  #' Path in which the scaler is saved (as a '.pickle' file) 
  path_to_scaler: \absolute\path\to\scaler\Scaler.pickle
  #' Path point to the folder in which the database file is stored
  path_to_file: \absolute\path\to\database
  #' Name of the database file used for test
  filename: "0_100_1_1100"



#' Input specifications
inp_spec:
  #' Neural network Inputs
  inputs: ['energy', 'dist_source_tally','dist_shield_tally','mfp','theta','fi']
  #' Inputs that are present in the database files.
  #' This input should be specified in case the Neural network Inputs (variable above) 
  #' is a subset of the actual database input set.
  database_inputs: null
  

  
# Output specifics
out_spec:
  #' Neural newtork Output
  output: "B"
  #' Use log-scale
  out_log_scale: True
  #' Database specifications
  #' Number of mesh subdivisions on x, y and z 
  mesh_dim: [80,100,35]





#' Neural network specifications
nn_spec:
  #' DNN architecture
  #' a list that gives to each layer the corresponing number of neurons
  #' note that f_maps[0] has to be equal to the number of inputs
  f_maps: [6,128,64,8]


