#' Paths to input and output quantities for processing binary files.
#' In this case, the inputs are the MCNP binary files containing meshtal results
#' while the output are the corresponding database files.
io_paths:
  #' Path to the folder in which to save files of the database
  database_folder_path: ""
  #' Path to the folder in which are stored MCNP results in binary file
  raw_path : ./examples/data_example/raw/ #\absolute\path\to\raw_files_folder\



#' Inputs to be considered in the database files.
inp_spec:
  #' the available inputs are:
  #' 'energy', 'slab_thickness', 'dist_source_tally', 'delta_t', 'angle', 'theta', 'fi', 'dist_source_wall', 'dist_wall_tally', 'mfp'
  inputs: ['energy', 'dist_source_tally','dist_shield_tally','mfp','theta','fi']


#' Output to be considered in the database files.
out_spec:
  #' the available outputs are:
  #' 'B', 'Dose'
  output : 'Dose'
  #' Number of mesh subdivisions on x, y and z 
  mesh_dim: [80,100,35]
  #' Add mcnp errors to the database
  errors: true


#' Geometric specifications of the irradiation configuration
geom_spec:
  #' coordinate of the wall
  p0 : 2000
  #' normal to shielding wall
  wall_normal : [0,1,0]
  #' position of the source
  source : [0,0,500]


#' Wall's material
mat_spec:
  #' list of element's atomic number in the material
  atomic_number: [ 1, 8, 11, 12, 13, 14, 16, 19, 20, 26]
  #' list of element's mass fraction in the material
  mass_fraction: [0.0056, 0.497500, 0.017100, 0.002600, 0.046900, 0.314700, 0.001300, 0.019200, 0.082800, 0.012400]
  #' density of the material
  ro : 2.2
  #' Path to flux to dose conversion coefficient
  path_to_dose_conversion : ./examples/data_example/resources/doseEquivalentConversion.txt
  #' Path to mass attenuation coefficient
  path_to_mass_att_coeff : ./examples/data_example/resources/massAttCoeff.xml



